circle: stop previous router version, switch from oauth2l to gcloud print-access-token
for #2315

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -193,19 +193,25 @@ jobs:
       - run:
           name: Migrate router traffic to new version
           command: |
-            cd /tmp
-            curl https://storage.googleapis.com/oauth2l/latest/linux_amd64.tgz | tar xz
-            cd -
+            oldver=$(gcloud app versions list --service=router --filter='traffic_split=1' --format='value(id)')
+            newver=$(gcloud app versions list --service=router --sort-by=~last_deployed_time --limit=1 --format='value(id)')
 
-            ver=$(gcloud app versions list --service=router --sort-by=~last_deployed_time --limit=1 --format='value(id)')
-            echo migrating all router traffic to $ver
-            gcloud -q app services set-traffic router --splits=${ver}=1
+            if [[ -z ${oldver} || -z ${newver} ]]; then
+              echo "Couldn't find current ${oldver} or new ${newver} version"
+              exit 1
+            elif [[ ${oldver} > ${newver} || ${oldver} == ${newver} ]]; then
+              echo "New version ${newver} is not after old version ${oldver}"
+              exit 1
+            fi
 
-            # drop router back to min_num_instances 1
-            /tmp/linux_amd64/oauth2l curl --scope=cloud-platform --credentials=/tmp/service_account_creds.json --url "https://appengine.googleapis.com/v1/apps/bridgy-federated/services/router/versions/${ver}?updateMask=automaticScaling.minTotalInstances" -- -X PATCH --data '{"automaticScaling": {"minTotalInstances": 1}, "env": "flexible"}' -H 'Content-Type: application/json'
+            echo Migrating all router traffic to $newver
+            gcloud -q app services set-traffic router --splits=${newver}=1
 
-            # TODO: stop previous router version. can't gcloud app versions stop;
-            # need to oauth2l with API?
+            # drop back to min_num_instances 1
+            curl -X PATCH -H "Authorization: Bearer $(gcloud auth print-access-token)" -H 'Content-Type: application/json' --data '{"automaticScaling": {"minTotalInstances": 1}, "env": "flexible"}' "https://appengine.googleapis.com/v1/apps/bridgy-federated/services/router/versions/${newver}?updateMask=automaticScaling.minTotalInstances"
+
+            echo Stopping old version $oldver
+            gcloud -q app versions stop --service=router ${oldver}
 
 
   delete-router-version:
@@ -219,7 +225,7 @@ jobs:
           command: |
             ver=$(gcloud app versions list --service=router --filter='traffic_split=0' --sort-by=~last_deployed_time --limit=1 --format='value(id)')
             if [[ -z "${ver}" ]]; then
-              echo "no non-serving router version found, skipping"
+              echo 'no non-serving router version found, skipping'
               exit 0
             fi
             # ideally we'd just stop it instead, but gcloud app versions stop only
